aws/eventbridge-kafka-connector

.github/workflows/format.yaml
NOTICE
pom.xml
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidator.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnector.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkTask.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriterRecord.java
src/main/java/software/amazon/event/kafkaconnector/auth/EventBridgeCredentialsProvider.java
src/main/java/software/amazon/event/kafkaconnector/exceptions/EventBridgePartialFailureResponse.java
src/main/java/software/amazon/event/kafkaconnector/exceptions/EventBridgeWriterException.java
src/main/java/software/amazon/event/kafkaconnector/util/PropertiesUtil.java
src/main/java/software/amazon/event/kafkaconnector/util/StatusReporter.java
src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigTest.java
src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidatorTest.java
src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkTaskTest.java
src/test/java/software/amazon/event/kafkaconnector/EventBridgeWriterTest.java

Closes: #21
Description
-----------
Enforce licenses in CI
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

ci: Enforce licenses

---

.github/workflows/build.yaml
.github/workflows/commits.yaml
.github/workflows/format.yaml
.github/workflows/git-secrets.yaml
commitlint.config.js
pom.xml

Description
-----------
Verify commit titles follow [conventional commit style](https://www.conventionalcommits.org/en/v1.0.0/) as described in CONTRIBUTING guide. This will make it easier to generate good releases notes and CHANGELOG files in the future.
Test Steps
-----------
Tested in CI with wrong/good commit.
Checklist:
----------
Related Issue
-----------
#23 

Check for conventional commits

---

README.md

Closes: #33
Description
-----------
Add delivery semantics to README
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Add delivery semantics to README

---

.github/workflows/e2e.yaml
e2e/connect-config-json.json
e2e/docker_compose.yaml
pom.xml
src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnectorIT.java

Description
-----------
First implementation of running Java integration tests with testcontainers.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

chore: java testcontainers integration tests

---

.github/workflows/e2e.yaml
e2e/docker_compose_redpanda.yaml
src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnectorIT.java

Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

ci: e2e with redpanda

---

.github/workflows/e2e.yaml

Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

ci: restructure e2e workflow

---

src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnectorIT.java

Description
-----------
Simplify integration test structure and add some more assertions
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

test: restructure json integration tests

---

pom.xml
src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java
src/main/java/software/amazon/event/kafkaconnector/batch/DefaultEventBridgeBatching.java
src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkTaskTest.java
src/test/java/software/amazon/event/kafkaconnector/EventBridgeWriterTest.java
src/test/java/software/amazon/event/kafkaconnector/TestUtils.java
src/test/java/software/amazon/event/kafkaconnector/batch/DefaultEventBridgeBatchingTest.java

Description
-----------
Sending proper batches to EventBridge w.r.t. 256kb size limit. A single batch of an item > 256kb is allowed, see discussion on #35.
Test Steps
-----------
```
$ mvn clean test
```
Checklist:
----------
Related Issue
-----------

support sending proper batches to EventBridge

---

.github/workflows/e2e.yaml
CONTRIBUTING.md
e2e/docker_compose.yaml
e2e/docker_compose_redpanda.yaml

Closes: #90
Description
-----------
Bump Kafka and Connect version to `3.5.1`.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
#90

ci: bump kafka connect version

---

README.md
e2e/connect-standalone.properties

Description
-----------
Test Steps
-----------
n/a
Checklist:
----------
Related Issue
-----------
#92 

Add note on quotas and configuring polling frequency for rate limiting

---

e2e/docker_compose_redpanda.yaml

Description
-----------
Bump redpanda version.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

ci: bump redpanda version

---

pom.xml
src/main/java/software/amazon/event/kafkaconnector/util/StatusReporter.java
src/test/java/software/amazon/event/kafkaconnector/util/StatusReporterTest.java

Closes #108.
Checklist:
----------
Related Issue
-----------

feat: remove Guava dependency

---

.github/workflows/e2e.yaml
e2e/docker_compose_confluent.yaml

See Confluent Platform 7.5 for new features and updates [1].
Closes #118.
[1]: https://www.confluent.io/blog/introducing-confluent-platform-7-5/
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
#118 

ci: add latest Confluent Kafka 7.5 to e2e test matrix

---

src/test/java/software/amazon/event/kafkaconnector/TestUtils.java
src/test/java/software/amazon/event/kafkaconnector/util/StatusReporterTest.java

Description
-----------
The list of appended logging events was modified by `StatusReporter`s logging and read by the test concurrently. 
Fixed by synchronizing access to this list and using a copy of it for assertions via `ListAppender#getLoggingEvents()`.
Fixes #129.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

fix: `ConcurrentModificationException` in `StatusReporterTest`

---

src/test/java/software/amazon/event/kafkaconnector/util/StatusReporterTest.java

Description
-----------
Instead of assert fixed values assert properties of log entries to prevent timing issues.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
The bug was introduced in [6cd990e].
Fixes #138.

fix: flaky test in `StatusReporterTest`

---

e2e/docker_compose.yaml
e2e/docker_compose_confluent.yaml
e2e/docker_compose_redpanda.yaml

Description
-----------
Update LocalStack in e2e tests to latest version.
Test Steps
-----------
Run CI.
Checklist:
----------
Related Issue
-----------

ci(deps): update LocalStack to 2.3.1

---

.github/workflows/e2e.yaml
e2e/docker_compose.yaml
e2e/docker_compose_confluent.yaml
e2e/docker_compose_redpanda.yaml

Description
-----------
Update E2E container image versions.
Test Steps
-----------
CI passes
Checklist:
----------
Related Issue
-----------

chore: update e2e container versions

---

cdk/lib/connectorConstruct.ts
cdk/tsconfig.json

Automatically change region in connector config based on CDK deployment
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Closes #149 

fix: Automatically change region in connector config based on CDK deployment

---

.github/workflows/e2e.yaml
CONTRIBUTING.md
e2e/docker_compose.yaml
e2e/docker_compose_confluent.yaml
e2e/docker_compose_redpanda.yaml

Closes #206.
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

ci: update Kafka/Redpanda to latest version in workflows

---

CONTRIBUTING.md
e2e/docker_compose.yaml
e2e/docker_compose_confluent.yaml
e2e/docker_compose_redpanda.yaml

Closes #196.
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

doc: add how to enable JVM debugging for Kafka Connect

---

CONTRIBUTING.md
README.md
pom.xml
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidator.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnector.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkTask.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java
src/main/java/software/amazon/event/kafkaconnector/auth/EventBridgeCredentialsProvider.java
src/main/java/software/amazon/event/kafkaconnector/batch/DefaultEventBridgeBatching.java
src/main/java/software/amazon/event/kafkaconnector/logging/ContextAwareLoggerFactory.java
src/main/java/software/amazon/event/kafkaconnector/util/PropertiesUtil.java
src/main/java/software/amazon/event/kafkaconnector/util/StatusReporter.java
src/test/java/software/amazon/event/kafkaconnector/TestUtils.java
src/test/java/software/amazon/event/kafkaconnector/batch/DefaultEventBridgeBatchingTest.java
src/test/java/software/amazon/event/kafkaconnector/logging/ContextAwareLoggerFactoryTest.java
src/test/java/software/amazon/event/kafkaconnector/util/StatusReporterTest.java

Description
-----------
Out git short commit SHA as a field in every log line to improve debugging.
Test Steps
-----------
`mvn clean test`
Checklist:
----------
Related Issue
-----------
#192

feat: add git short commit to log output

---

e2e/docker_compose.yaml
e2e/docker_compose_confluent.yaml
e2e/docker_compose_redpanda.yaml

Description
-----------
Update Localstack to v3.3.0.
Test Steps
-----------
```
mvn clean verify -Drevision=$(git describe --tags --always)
```
Checklist:
----------
Related Issue
-----------
#277.

ci: update Localstack to v3.3.0

---

e2e/docker_compose.yaml
e2e/docker_compose_confluent.yaml
e2e/docker_compose_redpanda.yaml

Description
-----------
Update Localstack to v3.4.0.
Test Steps
-----------
```sh
mvn clean verify -Drevision=$(git describe --tags --always)
```
Checklist:
----------
Related Issue
-----------
#286.

ci: update Localstack to v3.4.0

---

e2e/connect-config-s3.json
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidator.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java
src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidatorTest.java

Closes: #306
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

fix: rename s3 bucket config string

---

README.md
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java

Closes: #296
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

docs: add offloading to readme

---

e2e/docker_compose.yaml
e2e/docker_compose_confluent.yaml
e2e/docker_compose_redpanda.yaml

Description
-----------
Update Localstack to v3.5.0.
Test Steps
-----------
```sh
mvn clean verify -Drevision=$(git describe --tags --always)
```
Checklist:
----------
Related Issue
-----------
#321

ci: update Localstack to v3.5.0

---

.github/workflows/build.yaml
.github/workflows/commits.yaml
.github/workflows/e2e.yaml
.github/workflows/format.yaml
.github/workflows/git-secrets.yaml

Description
-----------
Use Github [Merge Queues](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) feature to simplify weekly maintenance with Dependabot PRs.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Use Github Merge Queues in CI

---

.github/workflows/e2e.yaml
CONTRIBUTING.md
e2e/docker_compose.yaml
e2e/docker_compose_confluent.yaml
e2e/docker_compose_redpanda.yaml

Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Bump Kafka versions

---

e2e/connect-config-s3.json
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidator.java
src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java

Description
-----------
Add dedicated configuration for S3 endpoint URI override.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Fixes #447.

fix: add dedicated configuration for S3 endpoint override

---

CONTRIBUTING.md

Closes: #195
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Explain how to fix mockito errors

---

src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkTask.java
src/main/java/software/amazon/event/kafkaconnector/auth/EventBridgeAwsCredentialsProviderFactory.java
src/test/java/software/amazon/event/kafkaconnector/auth/EventBridgeCredentialsProviderFactoryTest.java

Wrapped profile default supplier
Description
-----------
Added wrapped ProfileSupplier to catch Nullpointer and return default behavior instead.
Inspired by @agebhar1 - thank you!
Checklist:
----------
Related Issue
-----------
https://github.com/awslabs/eventbridge-kafka-connector/issues/396

Wrapped profile default supplier

---

.github/workflows/commits.yaml

Reduces CI noise on this soft-check which does not impact security of the pipeline
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Ignore dependabot commits in linter

---

.github/workflows/e2e.yaml
CONTRIBUTING.md
e2e/docker_compose.yaml
e2e/docker_compose_redpanda.yaml

Description
-----------
Add Apache Kafka 4.0.0 to e2e test matrix.
Test Steps
-----------
Run e2e tests.
Checklist:
----------
Related Issue
-----------
Closes #524.

ci: add Apache Kafka 4.0.0 to e2e test matrix

---

.github/workflows/e2e.yaml
e2e/docker_compose.yaml
e2e/docker_compose_confluent.yaml
e2e/docker_compose_redpanda.yaml

Description
-----------
Maintenance PR to update container images for `redpanda`, `confluent` and `localstack` images.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Update container images

---

.github/CODEOWNERS
README.md
pom.xml

Description
-----------
- update git links to point to `aws` org
- add note on support
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Update docs and configuration after graduation into aws org

---

README.md

Description
-----------
Add Amazon MSK installation instructions to readme
Test Steps
-----------
n/a
Checklist:
----------
Related Issue
-----------
Closes: #543

Add Amazon MSK installation instructions to readme

---

.github/workflows/format.yaml

Closes: #569
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Fix failing `fmt` workflow in CI due to maven change

---

README.md

Description
-----------
Add section on input transformations.
Test Steps
-----------
n/a
Checklist:
----------
Related Issue
-----------
Closes: #559

docs: add section for input transformation
