aws/eventbridge-kafka-connector

pom.xml
A report is generated in test phase and is available as HTML among others in `target/site/jacoco`.
https://www.eclemma.org/jacoco/trunk/index.html
=> setup »JaCoCo« for code coverage

commitlint.config.js
Closes: #34
Description
-----------
`commitlint` now only warns on non-lower-cased subject, instead of erroring out. See workflow output for example in this PR.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> `commitlint` warns on non-lower-cased subject

.github/workflows/build.yaml
Closes: #41
Description
-----------
Zips and uploads `target/` after build for introspection e.g., coverage., and manual testing. Retention days set to `5`.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> ci: upload artifacts after build

commitlint.config.js
commitlint errors when body is larger than 200 chars, instead of 100 (default config)
Closes: #44
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> ci: allow longer commitlint bodies

.github/workflows/build.yaml, .github/workflows/commits.yaml, .github/workflows/e2e.yaml, .github/workflows/format.yaml, .github/workflows/git-secrets.yaml, .github/workflows/release.yaml, e2e/connect-config-json.json, e2e/connect-log4j.properties, e2e/connect-standalone.properties, e2e/docker_compose.yaml, e2e/log4j.properties, pom.xml
Description
-----------
- Upgrade CI workflows to Ubuntu 22.04 (new E2E workflows require it because a newer `curl` version is required)
- Add basic E2E tests to the CI pipeline
- Build the connector (same as `build.yaml` for now)
- Deploy Kafka broker (w/ Kraft), Kafka Connect (both Bitnami) and [Localstack](https://localstack.cloud/)
- Deploy the connector
- Create SQS queue and EventBridge Rule/Target to send to SQS on pattern match
- Send an event
- Assert that the connector keeps running, i.e., no exception thrown after sending the event
- Dump logs so one can inspect if the event was sent to EventBridge*
> **Note**  
> Due to a [bug](https://github.com/localstack/localstack/issues/8472) in Localstack, we currently can't assert the event was delivered to SQS. Once this bug is fixed, …
=> Add basic E2E tests

.github/workflows/e2e.yaml
Connect seems to be flaky reporting status success too early
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> ci: add sleep before connector deployment

.github/workflows/e2e.yaml, e2e/docker_compose.yaml
Description
-----------
- Remove `kafkactl` image and use `kafka-console-producer.sh` instead to speed up the CI run.
- Use fixed names in `docker-compose`
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> ci: remove kafkactl

.github/workflows/e2e.yaml, e2e/docker_compose.yaml, src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnectorIT.java
Description
-----------
CI now runs E2E against multiple Kafka (Connect) versions (currently `3.4.0` and `3.4.1`). `docker-compose` file by default uses `3.4.1` unless overwritten with environment variable `KAFKA_VERSION`. Also dump Kafka environment variables on start to ease debugging.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> ci: multiple kafka version tests

e2e/docker_compose.yaml, e2e/docker_compose_redpanda.yaml, src/test/resources/logback-test.xml
Description
-----------
Disable `DEBUG` logging in testcontainers: configure `ch.qos.logback` used in tests to disable `DEBUG` level and reduce noice in E2E tests.
Use `2.2.0` tag for `localstack`: since a stable tag has been released after `2.1.0` with the required changes needed to run our E2E suite, this change uses a tagged `2.2.0` version for `localstack`.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
#86
=> Update E2E tests

src/main/java/software/amazon/event/kafkaconnector/mapping/DefaultEventBridgeMapper.java
Description
-----------
We pass `byte[]` to `createJSONFromByteArray` so there's no need for an additional `String` conversion since `readTree` accepts `byte[]` as well.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Closes: #88
=> perf: avoid string conversion

.github/workflows/e2e.yaml, e2e/docker_compose_confluent.yaml
Description
-----------
To continuously verify CI passes for #91 adding Confluent Platform as E2E test target. Note that this requires a parallel job in the E2E workflow due to the different versioning scheme of Confluent Platform.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Closes: #97
=> ci: run e2e with confluent

README.md
Description
-----------
Follow-up from #93 
Test Steps
-----------
Verified `consumer.override.max.poll.records` in Kafka Connect.
Checklist:
----------
Related Issue
-----------
=> Clarify Quota and Override in Docs

src/main/java/software/amazon/event/kafkaconnector/mapping/DefaultEventBridgeMapper.java
Description
-----------
Remove `putIfAbsent` calls to support older Kafka Connect environments (using Jackson <`2.13`) and replace deprecated `JsonNode` `put` calls (for `String` type values) with `set`.
Test Steps
-----------
Successfully tested with `docker.io/bitnami/kafka:2.7.0-debian-10-r124`, not throwing `Caused by: java.lang.NoSuchMethodError` exception anymore.
Checklist:
----------
Related Issue
-----------
Closes: #122
=> fix: remove putIfAbsent calls

CONTRIBUTING.md, e2e/docker_compose.yaml, e2e/docker_compose_confluent.yaml, e2e/docker_compose_redpanda.yaml, pom.xml, src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnectorIT.java
Description
-----------
Improve (Docker) compose files to use dynamic ports for Kafka Connect and Localstack to not depend on possible used ones. Integration tests are updated to use resolved exposed ports. Non used ports e.g. JMX are removed from compose files.
To use a dynamic port for Kafka the advertised listeners must be updated to the resolved port [1] which is not supported by Testcontainers 'Docker Compose Module' [2].
Closes #171.
[1]: https://github.com/testcontainers/testcontainers-java/blob/main/modules/kafka/src/main/java/org/testcontainers/containers/KafkaContainer.java
[2]: https://java.testcontainers.org/modules/docker_compose/
Test Steps
-----------
Run integration tests.
Checklist:
----------
Related Issue
-----------
By submitting this pull request, I confirm that you …
=> test: use dynamic ports for Kafka Connect and Localstack

README.md, src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java, src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidator.java, src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java, src/main/java/software/amazon/event/kafkaconnector/auth/EventBridgeCredentialsProvider.java, src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidatorTest.java
Add support to specify a profile from configuration and credential files to retrieve credentials so that each connector can be configured with different IAM settings if needed. This is currently not possible because in Kafka Connect Java system properties and environment variables, including `AWS_PROFILE`, are global for all connectors.
Closes: #191
Description
-----------
Test Steps
-----------
- Verify existing behavior with environment variables to retrieve credentials or using `aws.eventbridge.iam.role.arn` continue to work
- Verified that specifying a profile with `aws.eventbridge.iam.profile.name` and mounting AWS credential and configuration files into Kafka Connect works*
- Existing tests pass
- New test added
\* If one or more of the documented AWS credentials environment …
=> feat: add support for different authentication profiles

CONTRIBUTING.md, README.md, pom.xml, src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java, src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidator.java, src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnector.java, src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkTask.java, src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java, src/main/java/software/amazon/event/kafkaconnector/auth/EventBridgeCredentialsProvider.java, src/main/java/software/amazon/event/kafkaconnector/batch/DefaultEventBridgeBatching.java, src/main/java/software/amazon/event/kafkaconnector/logging/ContextAwareLoggerFactory.java, src/main/java/software/amazon/event/kafkaconnector/util/PropertiesUtil.java, src/main/java/software/amazon/event/kafkaconnector/util/StatusReporter.java, src/test/java/software/amazon/event/kafkaconnector/TestUtils.java, src/test/java/software/amazon/event/kafkaconnector/batch/DefaultEventBridgeBatchingTest.java, src/test/java/software/amazon/event/kafkaconnector/logging/ContextAwareLoggerFactoryTest.java, src/test/java/software/amazon/event/kafkaconnector/util/StatusReporterTest.java
Description
-----------
The log message is prefixed with the git commit id from the current build, similar to `git describe --abbrev --always --dirty`.
The prefix patern (RegEx) is: \[@[0-9a-f]+(-dirty)?]
Test Steps
-----------
`mvn clean test`
Checklist:
----------
Related Issue
-----------
#192, #216
=> feat: prefix each log messages w/ git commit id

.github/workflows/e2e.yaml, CONTRIBUTING.md, e2e/docker_compose.yaml
Description
-----------
There is a regression in CI with `bitnami/kafka` images using Debian versions > `debian-11-r1`. This was uncovered because Docker tags are mutable and a tag of `3.6.1` for example is moving across Debian/Bitnami releases. This change uses a more stable (yet still mutable) tag for the `bitnami/kafka` images.
Test Steps
-----------
CI E2E passes
Checklist:
----------
Related Issue
-----------
Closes: #222
=> `bitnami/kafka` Images use more specific tag

src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java, src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidator.java, src/main/java/software/amazon/event/kafkaconnector/mapping/DefaultDetailTypeMapper.java, src/main/java/software/amazon/event/kafkaconnector/mapping/DefaultEventBridgeMapper.java, src/main/java/software/amazon/event/kafkaconnector/mapping/DetailTypeMapper.java, src/test/java/software/amazon/event/kafkaconnector/DetailTypeMapperTest.java, src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidatorTest.java
Description
-----------
Adding DetailTypeMapper interface to be able to provide custom implementation for mapping a record based on the Kafka Topic or additional fields to EventBridge detailType. Current behavior will be set as default and is implemented by DefaultDetailTypeMapper.
Test Steps
-----------
Unit tests included
Checklist:
----------
Related Issue
-----------
#27 
=> Custom Topic to Detail Type mapping

pom.xml, src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnectorIT.java
Description
-----------
Improve existing integration test by:
* waiting for service endpoints instead of port (Kafka, LocalStack), port might by available but service is not ready
* use [Awailitility](http://www.awaitility.org/) consistent
* use [JsonPath](https://github.com/json-path/JsonPath) for asserting JSON content
Test Steps
-----------
```sh
mvn verify
```
Checklist:
----------
Related Issue
-----------
#273.
=> test: improve integration test

e2e/connect-config-s3.json, pom.xml, src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfig.java, src/main/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidator.java, src/main/java/software/amazon/event/kafkaconnector/EventBridgeWriter.java, src/main/java/software/amazon/event/kafkaconnector/cache/Cache.java, src/main/java/software/amazon/event/kafkaconnector/cache/FifoCache.java, src/main/java/software/amazon/event/kafkaconnector/cache/MessageDigestCacheKey.java, src/main/java/software/amazon/event/kafkaconnector/offloading/EventBridgeEventDetailValueOffloadingStrategy.java, src/main/java/software/amazon/event/kafkaconnector/offloading/NoOpEventBridgeEventDetailValueOffloading.java, src/main/java/software/amazon/event/kafkaconnector/offloading/S3EventBridgeEventDetailValueOffloading.java, src/main/java/software/amazon/event/kafkaconnector/util/ThrowingFunction.java, src/main/java/software/amazon/event/kafkaconnector/util/ThrowingFunctionApplyException.java, src/test/java/software/amazon/event/kafkaconnector/AbstractEventBridgeSinkConnectorIT.java, src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConfigValidatorTest.java, src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnectorS3IT.java, src/test/java/software/amazon/event/kafkaconnector/cache/FifoCacheTest.java, src/test/java/software/amazon/event/kafkaconnector/cache/MessageDigestCacheKeyTest.java, src/test/java/software/amazon/event/kafkaconnector/offloading/NoOpEventBridgeEventDetailValueOffloadingTest.java, src/test/java/software/amazon/event/kafkaconnector/offloading/S3EventBridgeEventDetailValueOffloadingTest.java
Description
-----------
EventBridge's PutEvents size limit is currently 256KB. Often, Kafka records are larger (default 1MB) and the connector drops (or DLQs, if configured) those records with a warning. By adding a new configuration property, the connector could send (sideline) those records to a configured event store, such as [S3](https://aws.amazon.com/s3/) e.g., by using the claim-check pattern, replacing the event payload with an S3 link (reference).
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
#110
=> Support sidelining large events/payloads to an external event store

src/test/java/software/amazon/event/kafkaconnector/AbstractEventBridgeSinkConnectorIT.java, src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnectorIT.java, src/test/java/software/amazon/event/kafkaconnector/EventBridgeSinkConnectorS3IT.java
Description
-----------
Improve integration test(s) by asserting Kafka connector task state is 'RUNNING' after execution of test case(s).
Test Steps
-----------
```
mvn clean verify
```
Checklist:
----------
Related Issue
-----------
Closes #297.
=> test: assert Kafka connector task state

src/main/java/software/amazon/event/kafkaconnector/auth/EventBridgeCredentialsProvider.java
Description
-----------
Leverage Default Profile Supplier for credentials reload as in: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-profiles.html#profile-reloading
Test Steps
-----------
TBD
Checklist:
----------
Related Issue
-----------
#357 
=> Leverage default profile supplier for credential reload

.github/workflows/e2e.yaml
Description
-----------
The Kafka Connector is running on the provided Java version of Kafka Connect, hence it's enough to run the e2e test(s) only once for each Kafka|Redpanda/Kafka Connect combination.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
Closes #367.
=> e2e: run only on one Java version

pom.xml, src/test/java/software/amazon/event/kafkaconnector/AbstractEventBridgeSinkConnectorIT.java
Description
-----------
With [tc-gh9370] Docker compose initialization is cleared. The shared (static) Docker compose instance is not valid in successive tests anymore.
Fixed it by running Docker compose for each test class.
[tc-gh9370]: https://github.com/testcontainers/testcontainers-java/pull/9370
Test Steps
-----------
```sh
mvn clean verify -Drevision=$(git describe --tags --always)
```
Checklist:
----------
Related Issue
-----------
=> build(deps-dev): bump testcontainers from 1.20.2 to 1.20.3

README.md
Closes: #124
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Explain handling of `null` keys and values (tombstones)

CONTRIBUTING.md, e2e/docker_compose.yaml, e2e/docker_compose_confluent.yaml, e2e/docker_compose_redpanda.yaml
Description
-----------
Updates Docker Compose instructions in `CONTRIBUTING` and removes `version` attribute from compose files to avoid warning.
Test Steps
-----------
Existing tests pass.
Checklist:
----------
Related Issue
-----------
#463 
=> Docker Compose updates

pom.xml, src/main/java/software/amazon/event/kafkaconnector/auth/EventBridgeAwsCredentialsProviderFactory.java, src/test/java/software/amazon/event/kafkaconnector/auth/EventBridgeCredentialsProviderFactoryTest.java
Final resolution for https://github.com/aws/eventbridge-kafka-connector/issues/396 because underlying issue was fixed in AWS SDK: https://github.com/aws/aws-sdk-java-v2/issues/5635
=> fix: removed credential workaround
